In [3]:
import csv
import pandas as pd
import numpy as np
import requests
from IPython.core.display import HTML
from bs4 import BeautifulSoup
import timeit
import urllib2

ImportError: No module named 'urllib2'

In [3]:
###Scraping Data
salary = []
company = []
location = []
jobs = []
jobdescription = []
for i in range(31):
    url = "https://angel.co/jobs#find/f!%7B%22locations%22%3A%5B%221664-New%20York%20City%2C%20NY%22%5D%2C%22roles%22%3A%5B%22Data%20Scientist%22%5D%2C%22salary%22%3A%7B%22min%22%3A20%2C%22max%22%3A200%7D%7D"
    index = 59
    char = i
    charplus = i + 1
    charplusstring = str(charplus)
    url2 = url[:index] + charplusstring + url[index + 1:]
    rm = requests.get(url2)
    soupm = BeautifulSoup(rm.content, "lxml")
    
    ###Appends job titles
    for d in soupm.findAll(class_='job-title'):
        jobs.append(d.text)
        
    ###Appends job descriptions
    for d in soupm.findAll(class_='job-description show-for-medium-up'):
        jobdescription.append(d.text)
    
    ###Appends salary, company, location.
    z = 0
    for d in soupm.findAll(class_='job-text'):
        if z % 3 == 0:
            salary.append(d.text)
        elif z % 3 == 1:
            company.append(d.text)
        else:
            location.append(d.text)
        
        z += 1

In [9]:
#salary
#company
#location
#jobs
#jobdescription

In [10]:
###Zipping them all together
info = zip(salary, company, location, jobs, jobdescription)

In [12]:
###Putting in DataFrame
df = pd.DataFrame(info)

In [15]:
###Naming Columns
df.columns = ('salary', 'company', 'location', 'title', 'description')

In [35]:
###Breaking location into State
df['state'] = [(x[-3:-1]) for x in df['location']]

u'---------------------------------------Fort Collins'

In [37]:
###Breaking location into City
df['delete'] = df['location'].str.replace('\n', '-------------------------')

In [39]:
df['delete2'] = [(x[-80:-29]) for x in df['delete']]

In [40]:
df['delete3'] = df['delete2'].str.replace('-', '')

In [42]:
df['city'] = df['delete3']

In [46]:
# del df['delete']
# del df['delete2']
# del df['delete3']
# del df['location']

In [48]:
###Removing \n from company
df['company'] = df['company'].str.replace('\n', '')

In [50]:
###Removing \n from title
df['title'] = df['title'].str.replace('\n', '')

In [51]:
###Removing \n from description
df['description'] = df['description'].str.replace('\n', '')

In [57]:
###Creating a column for low end of salary
df['low'] = [(x[18:22]) for x in df['salary']]

In [59]:
###Removing '$'
df['low'] = df['low'].str.replace('$', '')

In [61]:
###Removing 'k'
df['low'] = df['low'].str.replace('k', '')

In [63]:
###Removing '-'
df['low'] = df['low'].str.replace('-', '')

In [65]:
###Removing ','
df['low'] = df['low'].str.replace(',', '')

In [73]:
###Creating a column for high end of salary
df['high'] = [(x[-11:-6]) for x in df['salary']]

In [80]:
###Removing '$'
df['high'] = df['high'].str.replace('$', '')

In [81]:
###Removing 'k'
df['high'] = df['high'].str.replace('k', '')

In [82]:
###Removing '-'
df['high'] = df['high'].str.replace('-', '')

In [83]:
###Removing ','
df['high'] = df['high'].str.replace(',', '')

In [85]:
###Fixing '\nFull'
df['high'] = df['high'].str.replace('\nFull', '')

,salary,company,title,description,state,city,low,high
0,\nFull-Time | Pay: $125k - $150k/year\n,Sancus Associates,Associate Data Science,"Associate Data Scientist AdTech $125,000-150,0...",DC,District of Columbia,125,150
1,\nFull-Time | Pay: $90k - $110k/year\n,Analytic Recruiting,"Associate, data Science and market Intelligence","Associate, data Science and market Intelligenc...",NY,New York,90,110
2,\nFull-Time\n,Tech Mahindra,BI Data Engineer,Position Title: BI Data Engineer Location: New...,OH,New Albany,,
3,\nFull-Time | Pay: $32k - $50k/year\n,Challenge Charter School,6th grade Science & Language Arts Teacher - Mi...,Arizona’s 1st Official Core Knowledge® School;...,AZ,Glendale,32,50
4,\nFull-Time | Pay: $150k - $200k/year\n,CyberCoders,Senior Data Scientist - be the first Data Scie...,This position is open as of 10/17/2016. Senior...,CA,Marina del Rey,150,200
5,\nFull-Time | Pay: $50k - $70k/year\n,Medix,Research Scientist,Research Scientist This Research Scientist wil...,TX,Dallas,50,70
6,\nFull-Time | Pay: $0 - $100k/year\n,BIG WEDNESDAY DIGITAL,Junior Data Scientist - global eCommerce - Ban...,Junior Data Scientist - global eCommerce leade...,MD,Baltimore,0,100
7,\nFull-Time | Pay: $80k - $120k/year\n,Burnett Specialists,Data Scientist,Job Reference #: 41-1014TBD-16CT Data Scientis...,TX,Houston,80,120
8,\nFull-Time | Pay: $0 - $100k/year\n,BIG WEDNESDAY DIGITAL,Senior/Lead/NLP- Data Scientist - Bangkok role...,Senior/Lead/NLP- Data Scientist - Bangkok base...,WA,Seattle,0,100
9,\nFull-Time | Pay: 0 - 125k /year\n,Kelly Scientific Resources,"Sr. Manager, Medical Data Methodology",Kelly Clinical and a highly reputable pharmace...,MA,Cambridge,0,125
10,\nFull-Time | Pay: $0 - $100k/year\n,BIG WEDNESDAY DIGITAL,Data Scientist / Machine Learning Expert - Ban...,Data Scientist / Machine Learning Expert Pleas...,MA,Boston,0,100
11,\nFull-Time | Pay: $80k - $100k/year\n,endevis,Data Integration Developer,Endevis talent acquisition firm is working wit...,OH,Toledo,80,100
12,\nFull-Time | Pay: $100k - $150k/year\n,CyberCoders,Data Product Manager,This position is open as of 10/17/2016. Data P...,CA,San Francisco,100,150
13,\nFull-Time | Pay: $130k - $140k/year\n,Protege Hunters,Sales Engineer - Data Loss Protection Platform,TECHNICAL SALES ENGINEER - DATA SECURITY / DAT...,NY,New York,130,140
14,\nFull-Time | Pay: $0 - $100k/year\n,BIG WEDNESDAY DIGITAL,Lead Data Scientist / Data Scientist Manager -...,Lead Data Scientist (Bangkok) - FULL RELOCATIO...,CA,Palo Alto,0,100
15,\nFull-Time | Pay: $115k - $135k/year\n,Confidential,Lead Big Data Engineer,Please send resume in Word format if you are i...,NY,Harrison,115,135
16,\nFull-Time | Pay: $70k - $90k/year\n,Hellickson Associates,Data Center Engineer -Cisco,My client an IT services provide has an immedi...,WA,Spokane,70,90
17,\nFull-Time | Pay: $80k - $125k/year\n,Emerald Resource Group,Data Architect,Data Architect - Healthcare Direct Hire/FTE Co...,OH,Columbus,80,125
18,\nFull-Time | Pay: $40k - $50k/year\n,"Network Technologies International, Inc.",GIS Analyst I,Geographic Information Systems Analyst We are ...,AZ,Scottsdale,40,50
19,"\nFull-Time | Pay: $56,400/year\n",Cottonwood Financial,RISK ANALYST / STATISTICIAN,Reporting to the head of Risk and working clos...,TX,Irving,56,6400
20,\nFull-Time | Pay: $75k - $140k/year\n,Personnel Services Inc,Manager Field Agronomy,"Manager Field Agronomy LOCATION: Kansas City, ...",MO,Kansas City,75,140
21,\nFull-Time\n,Concurrent Technologies Corporation,SENIOR PRINCIPAL DATA SCIENTIST,"AtConcurrent Technologies Corporation (CTC), w...",PA,Johnstown,,
22,\nFull-Time | Pay: $100k - $130k/year\n,CyberCoders,Big Data Engineer,This position is open as of 10/17/2016. Big Da...,MA,Somerville,100,130
23,\nFull-Time | Pay: $130k - $150k/year\n,CyberCoders,Chief Data Scientist,This position is open as of 10/17/2016. Chief ...,UT,Salt Lake City,130,150
24,\nFull-Time | Pay: $10k - $150k/year\n,Aerotek,Data Scientist,Now hiring Data Scientists on DARPA's Net Defe...,VA,Arlington,10,150
25,\nFull-Time | Pay: $130k - $150k/year\n,CyberCoders,Chief Data Scientist,This position is open as of 10/17/2016. Chief ...,UT,Salt Lake City,130,150
26,\nFull-Time | Pay: $10k - $150k/year\n,Aerotek,Data Scientist,Now hiring Data Scientists on DARPA's Net Defe...,VA,Arlington,10,150
27,\nFull-Time | Pay: $70k/year\n,Confidential,Marketing Data Analyst,Marketing Data Analyst Position Summary The Ma...,MO,St. Louis,70,70
28,"\nFull-Time | Pay: $81,640 - $102,674/year\n",City and County of San Francisco,Data Clean Up and Conversion Lead,Data Clean Up and Conversion Lead $39.25 - $49...,CA,San Francisco,81,2674
29,"\nFull-Time | Pay: $94,484 - $118,872/year\n",City and County of San Francisco,Data Conversion Strategy Supervisor,Data Conversion Strategy Supervisor $45.43 - $...,CA,San Francisco,94,8872
...,...,...,...,...,...,...,...,...
701,\nFull-Time | Pay: $150k - $180k/year\n,Emerald Resource Group,Manager of Software Engineering - Robotics,Manager of Software Engineering - Robotics Eme...,OH,Strongsville,150,180
702,\nFull-Time | Pay: $115k - $130k/year\n,Emerald Resource Group,Sr. ECommerce Manager,Sr. ECommerce Manager Emerald Resource Group i...,OH,Cleveland,115,130
703,\nFull-Time | Pay: $100k - $120k/year\n,CyberCoders,Technical Writer,This position is open as of 10/17/2016. Techni...,CA,Redwood City,100,120
704,\nFull-Time | Pay: $65k - $80k/year\n,Cogensia,"Senior Analyst, Strategic & Analytic Solutions...",Cogensia is intelligence that compels; we are ...,IL,Schaumburg,65,80
705,\nFull-Time | Pay: $60k - $120k/year\n,Smiths Medical,Field Support Specialist,"AtSmiths Medical, we are passionate about impr...",NY,New York,60,120
706,\nFull-Time | Pay: $35k - $37k/year\n,The Dubin Group,Project Assistant,"Overview: Job ID 8929 Our client, a Clinical T...",PA,Wayne,35,37
707,\nFull-Time | Pay: $115k - $125k/year\n,Total Wine & More,IT Security Engineer,Why Apply? Is it important for you be excited ...,DC,Washington,115,125
708,\nFull-Time\n,Sartori Company,Consumer Insights Manager,world award-winning cheeseto the finest retail...,WI,Plymouth,,
709,\nFull-Time | Pay: $120k - $135k/year\n,pathwayRP,Clinical Research Business Dev Manager,Our client is seeking a Business Development M...,PA,Philadelphia,120,135
710,\nFull-Time | Pay: $50k/year\n,CSU,Research Associate 1,Description of Work Unit: Human Development an...,CO,Fort Collins,50,50
711,"\nSeasonal/Temp | Pay: $38k - $41,500/year\n",Ultimate,Human Resource Coordinator,A client in the Maryland Heights area is seeki...,MO,Saint Louis,ay:,1500
712,\nFull-Time | Pay: $35k/year\n,Community Support Advocates,Case Manager,Provides care coordination for members; coordi...,IA,Des Moines,35,35
713,\nFull-Time | Pay: $18k - $20k/year\n,Aerotek,Lab Associate - Project Management,Aerotek Scientific is looking for Lab Techs in...,CA,Valencia,18,20
714,\nFull-Time | Pay: $32k - $45k/year\n,The Institute for Transfusion Medicine,IT Help Desk Analyst,The IT Help Desk Analyst Delivers 1st level He...,PA,Pittsburgh,32,45
715,\nFull-Time | Pay: $125k - $155k/year\n,Robert Half Technology,Sr. Great Plains Developer send: Nader.Ali@rht...,Ref ID: 00350-9500206009 Classification: Softw...,CA,La Habra,125,155
716,\nFull-Time\n,Pride Industries,Case Manager,PRIDE Industries is a fast-paced company with ...,CA,Roseville,,
717,\nFull-Time | Pay: $75k - $110k/year\n,CyberCoders,"Bioinformatics Scientist - ""Top 10 Pharma/Biot...",This position is open as of 10/17/2016. Bioinf...,CA,Menlo Park,75,110
718,\nFull-Time | Pay: $70k - $80k/year\n,Ajilon Professional Staffing,Marketing Specialist,"Marketing Specialist Mount Olive, NJ $60-80k O...",NJ,Mount Olive Township,70,80
719,\nFull-Time | Pay: $115k - $135k/year\n,Confidential,Storage Engineer - Senior OR Lead Storage Engi...,Role & Responsibilities - Responsible for effe...,MA,Burlington,115,135
720,\nFull-Time | Pay: $95k - $102k/year\n,Apple & Associates,Clinical Support Specialist,Our client is a leading manufacturer of Medica...,GA,Atlanta,95,102
721,\nFull-Time | Pay: $140k - $170k/year\n,The Ascent Services Group,Associate Director of Strategic IT and Telecom...,Job Title: Associate Director of Strategic IT ...,MA,Billerica,140,170
722,\nFull-Time | Pay: $35k - $50k/year\n,Randstad USA,Payroll Specialist - Raleigh,SEEKING PAYROLL SPECIALIST IN RALEIGH! PLEASE ...,NC,Raleigh,35,50
723,\nFull-Time | Pay: $80k/year\n,Affirma Consulting,Microsoft Dynamics CRM Developer,At Affirma Consulting the CRM Practice is resp...,WA,Bellevue,80,80
724,\nFull-Time | Pay: $40k - $60k/year\n,BrainWorks,Recruiting Account Executive,Recruiting Account Executive: LEARN TO BE A RE...,NJ,New Providence,40,60
725,\nFull-Time | Pay: $140k - $170k/year\n,The Ascent Services Group,Associate Director of Strategic IT and Telecom...,Job Title: Associate Director of Strategic IT ...,MA,Billerica,140,170
726,\nFull-Time | Pay: $35k - $50k/year\n,Randstad USA,Payroll Specialist - Raleigh,SEEKING PAYROLL SPECIALIST IN RALEIGH! PLEASE ...,NC,Raleigh,35,50
727,\nFull-Time | Pay: $80k/year\n,Affirma Consulting,Microsoft Dynamics CRM Developer,At Affirma Consulting the CRM Practice is resp...,WA,Bellevue,80,80
728,\nFull-Time | Pay: $40k - $60k/year\n,BrainWorks,Recruiting Account Executive,Recruiting Account Executive: LEARN TO BE A RE...,NJ,New Providence,40,60
729,\nFull-Time | Pay: $45k - $54k/year\n,Chickasaw Nation Industries,Policy Analyst (FDA OIP & OPHT),In support of the U.S. Department of Health an...,MD,Silver Spring,45,54
730,\nFull-Time\n,Genpact Pharmalink,"Associate Program Director, Commercial RA","Associate Program Director, PRC (E4) is an exp...",CA,San Francisco,,

In [87]:
#df['hightest'] = [(x[-11:-6]) for x in df['salary']]

df['hightest'] = [(x[-11:-6]) if len(df['high'] == 4) for x in df['salary']  else df['low'] + 10]

SyntaxError: invalid syntax (<ipython-input-87-f978ff955166>, line 3)